networks:
  laravel:
    driver: bridge

services:
  shorturl-nginx:
    image: nginx:alpine
    container_name: shorturl-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7000:80"
    volumes:
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
    depends_on:
      - shorturl
    networks:
      - laravel

  shorturl:
    build:
      context: .
      dockerfile: dockerize/php/Dockerfile
    container_name: shorturl
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel

  shorturl-db:
    image: mysql:latest
    container_name: shorturl-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: dockerize/vuejs/Dockerfile
    ports:
      - '5173:8080'
    volumes:
      - ./shorturl-fe:/app
      - /app/node_modules
    networks:
      - laravel
volumes:
  dbdata:
    driver: local
